### ISSUE TITLE
Add dynamodb support 

### ISSUE THREAD

**Issue by srjchauhan** [srjchauhan/S3_image_upload#2]
The data that needs to be stored are:
1. Name of the image (the name received in the request)
2. Original link of the image (the link received in the request)
3. Path to the image in S3 (bucket + key name)
4. Timestamp of when the image was stored in S3

**Comment by z4id** [comment]
@srjchauhan have you started work on this enhancement ?

Otherwise I can work on it.

**Comment by srjchauhan** [comment]
@z4id  i have not started working on it. feel free to contribute

**Comment by srjchauhan** [comment]
I needed the feature so i created it.closing issue
